name: Generate Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SVG Cards
        run: |
          # Fetch Stats Card
          curl -s "https://github-readme-stats-psi-eight-83.vercel.app/api?username=AmineMabrouk17&show_icons=true&hide_border=true&bg_color=0d1117&title_color=00f2fe&icon_color=00f2fe&text_color=c9d1d9" -o stats.svg

          # Fetch Top Languages Card
          curl -s "https://github-readme-stats-psi-eight-83.vercel.app/api/top-langs/?username=AmineMabrouk17&layout=compact&hide_border=true&bg_color=0d1117&title_color=00f2fe&text_color=c9d1d9" -o top-langs.svg

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Update stats cards" || exit 0
          git push
